### PR TITLE
56 a team walmart show nodebf

### PR DESCRIPTION
**Pull request by noahcollins**

### CODE REVIEW

**Comment by dshaw** [comment]
Hmm, pretty sure we don't want to delete those files.

**Comment by noahcollins** [comment]
D'oh. Sorry. Hold please.

**Comment by noahcollins** [comment]
Okay, fixed it. I've introduced some history funk on 53-a-very-meta-show.md (with 07543c9 & 398b3e7) but the result is correct.

**Comment by nizaroni** [comment]
I think you may need to rebase on @nodeup's master before merging.

**Comment by noahcollins** [comment]
Thank you @khalifenizar - that makes way more sense than what I was trying to do :) Will do this soon.

**Comment by nizaroni** [comment]
You can edit or remove commits you don't like before you merge with an interactive rebase. Here's a nifty little guide: https://help.github.com/articles/interactive-rebase.

DISCLAIMER: Don't mess with commits that are already in the main repo branch. Commits that still live only in your fork are okay to tweak though.

**Comment by noahcollins** [comment]
Fixed it, I believe. Thanks again @khalifenizar for your assistance.

**Comment by dshaw** [comment]
Thank you @noahcollins @khalifenizar!

**Pull request merged**
